# -*- coding: utf-8 -*-
"""Softmax_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wr-zSegTSN4Xedj4NjmKz_MaWW8i5fep
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from zipfile import ZipFile
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, roc_auc_score, RocCurveDisplay
)

zip_path = "/content/online+shoppers+purchasing+intention+dataset (1).zip"   # CHANGE THIS to your actual ZIP filename

with ZipFile(zip_path, 'r') as z:
    z.extractall("/content/")

import os
os.listdir("/content/")

df = pd.read_csv("/content/online_shoppers_intention.csv")
df.head()

df = df.copy()

# Identify categorical and numeric columns
cat_cols = df.select_dtypes(include=['object', 'bool']).columns
num_cols = df.select_dtypes(include=['float64', 'int64']).columns

# Label encoding
le = LabelEncoder()
for col in cat_cols:
    df[col] = le.fit_transform(df[col])

# Define X and y
X = df.drop("Revenue", axis=1)
y = df["Revenue"]

# Scaling numerical columns
scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])

sm = SMOTE(random_state=42)
X_resampled, y_resampled = sm.fit_resample(X, y)

print("Before SMOTE:", y.value_counts())
print("After SMOTE:", y_resampled.value_counts())

X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled,
    test_size=0.20,
    random_state=42,
    stratify=y_resampled
)

softmax_model = LogisticRegression(
    multi_class='multinomial',
    solver='lbfgs',
    max_iter=500
)

softmax_model.fit(X_train, y_train)

y_pred = softmax_model.predict(X_test)
y_proba = softmax_model.predict_proba(X_test)[:, 1]

acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc = roc_auc_score(y_test, y_proba)

print("Accuracy:", acc)
print("Precision:", prec)
print("Recall:", rec)
print("F1 Score:", f1)
print("ROC AUC:", roc)

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap="Blues")
plt.title("Confusion Matrix - Softmax Regression")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

